### PR TITLE
Support for redis password authentication.

### PR DESCRIPTION
**Pull request by hcalsos**
Added support for password protected redisservers.
Passwords are supplied via URIs userinfo.

### CODE REVIEW

**Comment by magro** [comment]
Great, thanks for the PR! Can you please update the documentation in the wiki with this?

**Comment by hcalsos** [comment]
I have updated the wiki with configuration options.

**Comment by magro** [comment]
Great, thanks! (better late than never ;-))

**Comment by beneshadyhw** [comment]
I encountered a problem that my password for Redis contains a character "@", which cause a format error when connecting to my redis node. I tried url encoding ("%40") but it's not working as well. Any chance i can work around with it except changing the password of it? much thanks~

**Pull request merged**
