### PR TITLE
Support for Redis Cluster

### PR DESCRIPTION
**Pull request by xavierfacq**
Hi, 

This is a new pull request to add support for **Redis Cluster**.

A new storage client have been added : **RedisClusterStorageClient.java**
A new optional parameter is available: **redisMode** (normal or cluster)

If the redisMode is setted to "cluster", the RedisClusterStorageClient will be used instead of RedisStorageClient.

```
    <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
        memcachedNodes="redis://172.16.50.12:7000,redis://172.16.50.12:7001,redis://172.16.50.12:7002"
        sticky="false"
        requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
        redisMode="cluster"
     />

```

### CODE REVIEW

**Comment by magro** [comment]
@xavierfacq thanks for the PR, and sorry for the late response ;-)

Can you squash the commits please?

**Comment by xavierfacq** [comment]
Sorry but this pull request have been done there is so many time that I
don't remember what have been done in...
May be I should take the code or get the PR as it is.

2018-03-14 23:36 GMT+01:00 Martin Grotzke <notifications@github.com>:

**Comment by gdubicki** [comment]
Can we get this merged please, @magro @sirdsoriano @xavierfacq ?

**Comment by dom-nie** [comment]
@xavierfacq @sirdsoriano @magro 
Any chance to get this merged?

**Comment by xavierfacq** [comment]
To far away to remember :-(

**Comment by magro** [comment]
@dom-nie you could pick the branch, squash commits and submit a new PR. WDYT?

**Comment by whigley** [comment]
When do you plan to add redis mode option to tc9?

**Comment by LLY-SC** [comment]
已收到你的邮件，我会尽快与你联系回复！谢谢！！

**Pull request closed without merging**
